;;; fcitx-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fcitx.el

(autoload 'fcitx-check-status "fcitx")
(autoload 'fcitx-prefix-keys-add "fcitx" "\


(fn &rest PREFIX-KEYS)" t)
(autoload 'fcitx-prefix-keys-turn-on "fcitx" "\
Turn on `fcixt-disable-prefix-keys'." t)
(autoload 'fcitx-prefix-keys-turn-off "fcitx" "\
Turn off `fcixt-disable-prefix-keys'." t)
(autoload 'fcitx-prefix-keys-setup "fcitx" nil t)
(autoload 'fcitx-evil-turn-on "fcitx" nil t)
(autoload 'fcitx-evil-turn-off "fcitx" nil t)
(autoload 'fcitx-M-x-turn-on "fcitx" nil t)
(autoload 'fcitx-M-x-turn-off "fcitx" nil t)
 (autoload 'fcitx-shell-command-turn-on "fcitx" "Enable `shell-command' support" t)
 (autoload 'fcitx-shell-command-turn-off "fcitx" "Disable `shell-command' support" t)
 (autoload 'fcitx-eval-expression-turn-on "fcitx" "Enable `shell-command' support" t)
 (autoload 'fcitx-eval-expression-turn-off "fcitx" "Disable `eval-expression' support" t)
(autoload 'fcitx-read-funcs-turn-on "fcitx" nil t)
(autoload 'fcitx-read-funcs-turn-off "fcitx" nil t)
(autoload 'fcitx-aggressive-minibuffer-turn-on "fcitx" nil t)
(autoload 'fcitx-aggressive-minibuffer-turn-off "fcitx" nil t)
(autoload 'fcitx-isearch-turn-on "fcitx" nil t)
(autoload 'fcitx-isearch-turn-off "fcitx" nil t)
(autoload 'fcitx-org-speed-command-turn-on "fcitx" nil t)
(autoload 'fcitx-org-speed-command-turn-off "fcitx" nil t)
(autoload 'fcitx-read-only-turn-on "fcitx" nil t)
(autoload 'fctix-read-only-turn-off "fcitx" nil t)
(autoload 'fcitx-default-setup "fcitx" "\
Default setup for `fcitx'." t)
(autoload 'fcitx-aggressive-setup "fcitx" "\
Aggressive setup for `fcitx'." t)
(register-definition-prefixes "fcitx" '("fcitx-"))

;;; End of scraped data

(provide 'fcitx-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fcitx-autoloads.el ends here
